### ISSUE TITLE
Two additional suggestions

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#13]
Is it possible to add a function to continue finishing the script if it was interrupted?

I have not been able to complete downloading the stats from a large YouTube channel, it errored out, I'm not sure if it was a network error from running for over two days, or something else. It would be very useful if I could continue where it left off, rather than starting again from scratch in the blind hope it will finish the second time.

I also think it would be nice if you had the option to export the information to CSV with each separate piece of data in individual cells.

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/data/data/com.termux/files/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/data/data/com.termux/files/usr/lib/python3.8/socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 7] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/utils.py", line 2725, in https_open
    return self.do_open(functools.partial(
  File "/data/data/com.termux/files/usr/lib/python3.8/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 7] No address associated with hostname>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/totalsize", line 8, in <module>
    sys.exit(cli())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/totalsize/total.py", line 325, in cli
    print_report(args.url, args.format_filter, more_info=args.more_info)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/totalsize/total.py", line 283, in print_report
    for entry in playlist.gen_info():
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/totalsize/total.py", line 169, in gen_info
    for media in self._medias:
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 301, in _entries
    more = self._download_json(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 888, in _download_json
    res = self._download_json_handle(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 867, in _download_json_handle
    res = self._download_webpage_handle(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 272, in _download_webpage_handle
    return super(YoutubeBaseInfoExtractor, self)._download_webpage_handle(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 660, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 645, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: <urlopen error [Errno 7] No address associated with hostname> (caused by URLError(gaierror(7, 'No address associated with hostname')))
$

**Comment by theychx** [comment]
I'm not keen on implementing "continue", as I've explained in https://github.com/theychx/totalsize/issues/8#issuecomment-561783490.

Your traceback suggests that there was a dropout in your internet connection. I've implemented rudimentary retry behaviour, so that processing is more robust in these cases.

I've also implemented csv export.
