### ISSUE TITLE
Some media urls make totalsize crash during extraction

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#18]
I'm getting this error after some time during the -m command.

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature
    video_id, player_url, s
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1356, in <lambda>
    return lambda s: initial_function([s])
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/user/.local/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Unsupported JS expression '['; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by theychx** [comment]
It would be useful if you could post the full command you used (including url), so there is some context for the traceback.

**Comment by beskhu3epnm** [comment]
This is the full command I used:
`totalsize -m https://www.youtube.com/user/THEKINGOFHATEVLOGS/videos >> THEKINGOFHATEVLOGS-Totalsize.txt`

**Comment by theychx** [comment]
The cause of your traceback was fixed in `youtube-dl 2020.1.24`.
I can't seem to reproduce this, even after having downgraded `youtube-dl` to a previous version. I get a few 404's, but nothing that makes `totalsize` crash.
But anyway, even if there is an info extraction error, that shouldn't make `totalsize` crash, so there's still some fixes that need to be done on my end. Feel free to post specific media urls (not playlist urls) here that make `totalsize` crash, so I can fix this.

**Comment by theychx** [comment]
`0.4.1` is out! Should have much better error handling.

**Comment by beskhu3epnm** [comment]
Thanks the recent update fixed the issue.
