### ISSUE TITLE
Media count should be set to 'None' for unsupported URLs

### ISSUE THREAD

**Issue by anonieee** [theychx/totalsize#22]
```
C:\>totalsize "https://google.com" --media
ERROR: Unsupported URL: https://www.google.com/
1
```
Media count seems to still produce a number even if the URL is unsupported. I think it's because it uses the fallback generic extractor and totalsize thinks that there's a media file.

Also on another note, I've encountered a strange error when the program encounters a NoneType in total filesize:
```
C:\Users\name>totalsize "https://google.com"
                                                                  Size
----------------------------------------------------------------------
ERROR: Unsupported URL: https://www.google.com/
Traceback (most recent call last):
  File "c:\users\name\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\name\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\AppData\Local\Programs\Python\Python38-32\Scripts\totalsize.exe\__main__.py", line 7, in <module>
  File "c:\users\name\appdata\local\programs\python\python38-32\lib\site-packages\totalsize\total.py", line 432, in cli
    print_report(playlist, more_info=more_info)
  File "c:\users\name\appdata\local\programs\python\python38-32\lib\site-packages\totalsize\total.py", line 344, in print_report
    print_report_line(entry=entry, msg="no size", more_info=more_info, err=True)
  File "c:\users\name\appdata\local\programs\python\python38-32\lib\site-packages\totalsize\total.py", line 323, in print_report_line
    print(fstr.format(**report_line), file=sys.stderr if err else sys.stdout)
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by theychx** [comment]
Thank you for reporting this, I'll work something out.

**Comment by theychx** [comment]
`0.4.2` is out! For fields where there is no data collected, we now print `-1`.

**Comment by anonieee** [comment]
Thank you it works!
```
totalsize "https://google.com"  --media --size
ERROR: Unsupported URL: https://www.google.com/
0
-1
```
Though one nitpick is that the behaviour of --media and --size is a bit inconsistent, but I can deal with that.

**Comment by theychx** [comment]
> Though one nitpick is that the behaviour of --media and --size is a bit inconsistent

Howso?

**Comment by anonieee** [comment]
When there are no media files, the program prints out a zero, but when there's no filesize the program prints out a -1.

**Comment by theychx** [comment]
Oh, that's intentional. A media count of zero is plausible (like in your example), while a filesize of zero is not.

**Comment by anonieee** [comment]
Ahhh, I see makes sense.
