### ISSUE TITLE
KeyError: 'content_html'

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#29]
`totalsize -m https://www.youtube.com/playlist?list=PLG0nnBV58Jj8jS2NX43rFWYlQ0I1gf0v0 >> file.txt`
It runs into an error about half-way into the playlist.

Error message:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/totalsize", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.6/site-packages/totalsize/total.py", line 438, in cli
    print_report(playlist, more_info=more_info)
  File "/home/user/.local/lib/python3.6/site-packages/totalsize/total.py", line 348, in print_report
    for entry in playlist.gen_info():
  File "/home/user/.local/lib/python3.6/site-packages/totalsize/total.py", line 198, in gen_info
    for media in self._medias:
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 313, in _entries
    content_html = more['content_html']
KeyError: 'content_html'
```

**Comment by theychx** [comment]
Please upgrade `youtube-dl`.

**Comment by beskhu3epnm** [comment]
I updated youtube-dl before submitting this Issue. But in the previous few hours a new version has been released, and so I have updated it again. However, the issue still remains. Both Totalsize and youtube-dl are the latest version.
