### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by beskhu3epnm** [theychx/totalsize#4]
The process runs into errors pulling the data from some larger channels.
From a channel with 2,307 videos, the process stops at line 658, 591, 593, the three times I ran the same command. With an even larger channel with 64K videos, it stopped around 23K and 26K the two times I ran the same command.

Here is the output:
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2237, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/john/.local/bin/totalsize", line 11, in <module>
    sys.exit(cli())
  File "/home/john/.local/lib/python3.6/site-packages/totalsize/total.py", line 171, in cli
    get_totalsize(args.url, args.format_filter, report_mode=True)
  File "/home/john/.local/lib/python3.6/site-packages/totalsize/total.py", line 130, in get_totalsize
    for title, inaccurate, size in info:
  File "/home/john/.local/lib/python3.6/site-packages/totalsize/total.py", line 95, in get_info
    inaccurate, size = self._get_size(media)
  File "/home/john/.local/lib/python3.6/site-packages/totalsize/total.py", line 90, in _get_size
    return self._calc_size(best.get("requested_formats") or [best])
  File "/home/john/.local/lib/python3.6/site-packages/totalsize/total.py", line 67, in _calc_size
    self._ydl.extract_info(fragm_url)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 869, in process_ie_result
    extra_info=extra_info)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1927, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/john/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by theychx** [comment]
Thank you for reporting this.

The error is because of some video that is no longer available (or not available to you for other reasons, such as region restrictions). The default behaviour of youtube-dl is to abort if such an event occurs. Which I forgot about. I'll fix it in the coming days.

**Comment by theychx** [comment]
@beskhu3epnm Please try the new `0.1.2` release.

**Comment by beskhu3epnm** [comment]
Thanks for patching this so quick. It seems to have fixed the issue, I've successfully downloaded some channels. I'm going to continue to use it over the next few weeks and I'll inform you again if I encounter problems. totalsize has been very useful to me so far.

**Comment by theychx** [comment]
Good to hear!

**Comment by beskhu3epnm** [comment]
I'm sorry, but I've run into the same issue again. It allowed me to download some channels I couldn't before, but now I've hit a wall again.

Here is the output:
Traceback (most recent call last):
  File "/home/John/.local/bin/totalsize", line 11, in <module>
    sys.exit(cli())
  File "/home/John/.local/lib/python3.6/site-packages/totalsize/total.py", line 182, in cli
    get_totalsize(args.url, args.format_filter, report_mode=True)
  File "/home/John/.local/lib/python3.6/site-packages/totalsize/total.py", line 135, in get_totalsize
    for title, inaccurate, size in info:
  File "/home/John/.local/lib/python3.6/site-packages/totalsize/total.py", line 98, in get_info
    inaccurate, size = self._get_size(media)
  File "/home/John/.local/lib/python3.6/site-packages/totalsize/total.py", line 94, in _get_size
    return self._calc_size(best.get("requested_formats") or [best])
  File "/home/John/.local/lib/python3.6/site-packages/totalsize/total.py", line 67, in _calc_size
    fragm_url = media["fragment_base_url"] + fragments[2]["path"]
IndexError: list index out of range

**Comment by theychx** [comment]
`0.1.3` is out! Thank you for testing this!

**Comment by beskhu3epnm** [comment]
It's now running perfectly fine. Thanks.
